INSERT INTO PERSONA (EMPRESA_ID, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NRO_DOCUMENTO, FECHA_NACIMIENTO, PESO, ESTATURA,
GRUPO_SANGUINEO, DIRECCION, URBANIZACION, DEPARTAMENTO_ID, PROVINCIA_ID, DISTRITO_ID, TELEFONO_FIJO, TELEFONO_CELULAR, EMAIL)
VALUES (13, 'KIEL ROBERT', 'SAENZ', 'ZUÑIGA', '41296691', CURDATE(), 78.50, 1.71,
'O+', 'CALLE LOMA BELLA 282', 'PROLONGACION BENAVIDES', '15', '01', '40', '2790623', '989629998', 'kiel.saenz@yahoo.com');